In [2]:
from fastapi import APIRouter, Query, HTTPException
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime, timedelta
from collections import defaultdict
import pandas as pd
import json
import re
import sys

sys.path.insert(0, r"D:/A0_Project")  # 讓它優先被找到
from PI_SYSTEM.models.sql_db_connect import MySQLConnet
dbhandler = MySQLConnet('piaoi_density')
cim_dbhandler = MySQLConnet('cim_piaoi')
old_dbhandler = MySQLConnet('l6a01_project')

from PI_SYSTEM.models.density.cim_density_job import Config as DensityJobConfig
from PI_SYSTEM.models.density.API_Config import API_Config

In [6]:
tbn = 'cim_defect_202603_aoi200_capic500'
tbn = 'cim_pi_glass_202603'
df = cim_dbhandler.get_runs_delta_days(tbn, 3, 'test_time')
df.head()

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
0,AJ5R130WBK,2026-03-31 14:00:38,M195RTN01_RG,PI AOI,CF,803,CA0189,CAPIT203,80,0,0,24,56,CAPIC200,2026-03-31 11:08:46,2026-03-31 10:00:00,API
1,AJ5R130WA5,2026-03-31 13:57:15,M195RTN01_RG,PI AOI,CF,803,CA0189,CAPIT203,80,0,3,27,50,CAPIC200,2026-03-31 11:08:46,2026-03-31 10:00:00,API
2,AJ5R130W9G,2026-03-31 13:54:06,M195RTN01_RG,PI AOI,CF,803,CA0189,CAPIT203,56,0,0,20,36,CAPIC200,2026-03-31 11:08:46,2026-03-31 10:00:00,API
3,AJ5R130W9S,2026-03-31 13:50:50,M195RTN01_RG,PI AOI,CF,803,CA0189,CAPIT203,73,0,0,24,49,CAPIC200,2026-03-31 11:08:46,2026-03-31 10:00:00,API
4,AJ5R130W9K,2026-03-31 13:40:53,M195RTN01_RG,PI AOI,CF,803,CA0189,CAPIT203,115,0,3,46,66,CAPIC200,2026-03-31 11:08:46,2026-03-31 10:00:00,API

In [7]:
df.iloc[0,:].to_dict()

{'sheet_id_chip_id': 'AJ5R130WBK',
 'test_time': Timestamp('2026-03-31 14:00:38'),
 'model_no': 'M195RTN01_RG',
 'op_id': 'PI AOI',
 'abbr_cat': 'CF',
 'recipe_id': '803',
 'cassette_id': 'CA0189',
 'aoi': 'CAPIT203',
 'total_defect_qty': 80,
 'defect_size_o_qty': 0,
 'defect_size_l_qty': 0,
 'defect_size_m_qty': 24,
 'defect_size_s_qty': 56,
 'line_id': 'CAPIC200',
 'pi_time': Timestamp('2026-03-31 11:08:46'),
 'pi_hour': Timestamp('2026-03-31 10:00:00'),
 'pi_type': 'API'}

In [2]:
tbn = "aoi_inspection_default_spectable"
tb = old_dbhandler.get_table(tbn)
tb

         model glass_type   line_id  OOC  OOS Editor          modify_time drop
0    A101EAN01        TFT  CAPIC107  0.5  0.8     預設  2026-01-02 13:52:53    F
1    B070AAN01        TFT  CAPIC107  0.5  0.8     預設  2025-12-24 09:00:00    F
2    B070AAN1Y        TFT  CAPIC107  0.5  0.8     預設  2025-12-24 09:00:00    F
3    B080EAN05        TFT  CAPIC107  0.5  0.8     預設  2025-12-24 09:00:00    F
4    B101EAN02        TFT  CAPIC107  0.5  0.8     預設  2025-12-24 09:00:00    F
..         ...        ...       ...  ...  ...    ...                  ...  ...
724  M340QAR1A        TFT  CAPIC607  0.5  0.8     預設  2026-01-05 08:54:55    F
725  M270QAN06        TFT  CAPIC207  3.0  4.0     預設  2026-01-15 11:46:34    F
726  M270QAN06        TFT  CAPIC507  2.0  3.0     預設  2026-02-21 11:34:13    F
727  M270DANA0        TFT  CAPIC407  2.0  3.0     預設  2026-03-04 08:12:10    F
728  M270QAN07        TFT  CAPIC507  3.0  4.0     預設  2026-03-10 14:50:16    F

[729 rows x 8 columns]

In [ ]:
db = MySQLConnet('piaoi_inspection_density')
tbn = "inspection_api_summary_202604"
#tbn = "default_spec_table"
#rows = db.get_runs_delta_days(tbn, 2, 'pi_hour')
#rows
tb[tb['model'].str.contains("test")]
tb = db.get_table(tbn)
print(len(tb))

1079

In [26]:
#db = MySQLConnet('piaoi_inspection_density')
db = MySQLConnet('piaoi_inspection_density')
rdf = db.get_table('inspection_raw_table_202604')
sdf = db.get_table('inspection_summary_table_202604')

In [25]:
old_df = old_dbhandler.get_table('inspection_raw_table_202604')
db.save_table('inspection_raw_table_202604', old_df)

2026-04-08 11:16:58,768 - INFO - [save_table] piaoi_inspection_density.inspection_raw_table_202604 已寫入 201734 列（去除 0 重複）

201734

In [27]:
non_id = 0
non_sheet = 0
same1 = 0
same2 = 0
non_df = pd.DataFrame()
sheet_id_non_df = pd.DataFrame()
for (runid, sheet, ), s_raw in sdf.groupby(['RUN_ID', 'SHEET_ID']):
    s_len = float(s_raw['TOTAL_DEFECT_COUNT'].unique()[0])
    if s_len ==0: continue
    raw = rdf[(rdf['RUN_ID'] == runid) & (rdf['SHEET_ID'] == sheet)]
    
    if not raw.empty:
        
        if len(raw) != s_len and len(raw)!=1000:
            print("defect count fail")
            print(runid, sheet)
            print( s_raw)
            print(len(raw))
            print()
            print(raw)
            non_df = pd.concat([non_df, s_raw])
            same1 +=1
        else:
            same2 +=1
    else:
        print('runid fail: ', runid, sheet)
        print( s_raw)
        raw = rdf[(rdf['SHEET_ID'] == sheet)]
        if not raw.empty:
            print("-----runid fail 'SHEET_ID' ok ----")
            
            print(len(raw))
            print(raw)
            non_id +=1
        else:
            print("-----only 'SHEET_ID' also fail----")
            sheet_id_non_df = pd.concat([sheet_id_non_df, s_raw])
            non_sheet +=1
    #print('=====')

runid fail:  -2116673833.0 AA1EZ4020H
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
37604       71.0         OK          71.0   True  L6A  G101EAN2G

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
37604  G101EAN2G-CF  -2116673833.0 2026-04-08 10:00:41

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
37604  2026-04-08 10:00:18.000  AA1EZ4020H  CELL  CAPIC107                1.0

      TYPE
37604   CF
-----only 'SHEET_ID' also fail----
runid fail:  -2116674245.0 AA1EZ4024V
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
37183       71.0         OK          71.0   True  L6A  G101EAN2G

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
37183  G101EAN2G-CF  -2116674245.0 2026-04-08 08:42:07

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
37183  2026-04-08 08:41:45.000  AA1EZ4024V  CELL  CAPIC107                1.0

      TYPE
37183   CF
-----only 'SHEET_ID' also fail----
runid fail:  -2116674361.0 AL5H1427UH
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
37131       18.0         OK          17.0   True  L6A  G215HVN01

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
37131  G215HVN01-CF  -2116674361.0 2026-04-08 09:15:25

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
37131  2026-04-08 09:15:02.000  AL5H1427UH  CELL  CAPIC207               14.0

      TYPE
37131   CF
-----only 'SHEET_ID' also fail----
defect count fail
-2116674497.0 AL5H14283A
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36995       18.0         OK          17.0   True  L6A  G215HVN01

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36995  G215HVN01-CF  -2116674497.0 2026-04-08 08:50:42

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36995  2026-04-08 08:50:19.000  AL5H14283A  CELL  CAPIC207                4.0

      TYPE
36995   CF
3

          COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
198612   -102.882  -1743.972   True                   1.0                L
198613  -1201.614  -1755.153   True                   2.0                M
198614   -414.662  -1487.349   True                   3.0                S

        FAB FRONT_REVERSE                                         IMG_URL  \
198612  L6A            1N  http://10.97.138.179/20260408/AL5H14283A/1.jpg
198613  L6A            1P  http://10.97.138.179/20260408/AL5H14283A/2.jpg
198614  L6A            1N  http://10.97.138.179/20260408/AL5H14283A/3.jpg

         RECIPE_NAME         RUN_ID         SCAN_ENDTIME       SCAN_STARTTIME  \
198612  G215HVN01-CF  -2116674497.0  2026-04-08T08:50:42  2026-04-08T08:50:19
198613  G215HVN01-CF  -2116674497.0  2026-04-08T08:50:42  2026-04-08T08:50:19
198614  G215HVN01-CF  -2116674497.0  2026-04-08T08:50:42  2026-04-08T08:50:19

          SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
198612  AL5H14283A  N  CELL  CAPIC207                4.0
198613  AL5H14283A  N  CELL  CAPIC207                4.0
198614  AL5H14283A  N  CELL  CAPIC207                4.0
runid fail:  -2116674498.0 JT6A3XU9C
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
37028       36.0         OK          35.0   True  L6A  B140UAN08

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
37028  B140UAN08-TFT  -2116674498.0 2026-04-08 08:57:04

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
37028  2026-04-08 08:56:38.000  JT6A3XU9C  CELL  CAPIC507                3.0

      TYPE
37028  TFT
-----only 'SHEET_ID' also fail----
runid fail:  -2116674668.0 AA1EZ4020W
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36782       71.0         OK          71.0   True  L6A  G101EAN2G

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36782  G101EAN2G-CF  -2116674668.0 2026-04-08 07:42:30

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36782  2026-04-08 07:42:08.000  AA1EZ4020W  CELL  CAPIC107                1.0

      TYPE
36782   CF
-----only 'SHEET_ID' also fail----
runid fail:  -2116675013.0 L66A3VR8V
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36462       18.0         OK          16.0   True  L6A  G215HVN01

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36462  G215HVN01-TFT  -2116675013.0 2026-04-08 07:32:20

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36462  2026-04-08 07:31:58.000  L66A3VR8V  CELL  CAPIC207                5.0

      TYPE
36462  TFT
-----only 'SHEET_ID' also fail----
runid fail:  -2116675028.0 VP6G2NC52
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36481       12.0         OK          12.0   True  L6A  M340QAR1A

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36481  M340QAR1A-TFT  -2116675028.0 2026-04-08 07:01:19

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36481  2026-04-08 07:00:57.000  VP6G2NC52  CELL  CAPIC407                1.0

      TYPE
36481  TFT
-----only 'SHEET_ID' also fail----
runid fail:  -2116675040.0 JT6A3XT7Z
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36490       36.0         OK          36.0   True  L6A  B140UAN08

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36490  B140UAN08-TFT  -2116675040.0 2026-04-08 07:36:42

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36490  2026-04-08 07:36:16.000  JT6A3XT7Z  CELL  CAPIC507                3.0

      TYPE
36490  TFT
-----only 'SHEET_ID' also fail----
defect count fail
-2116675097.0 JT6A3XT7T
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36428       36.0         OK          35.0   True  L6A  B140UAN08

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36428  B140UAN08-TFT  -2116675097.0 2026-04-08 07:31:14

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36428  2026-04-08 07:30:48.000  JT6A3XT7T  CELL  CAPIC507                2.0

      TYPE
36428  TFT
1

        COORD_X      COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
196046  -164.02  -1435.57813   True                   1.0                S

        FAB FRONT_REVERSE                                       IMG_URL  \
196046  L6A            1N  http://10.97.138.17/20260408/JT6A3XT7T/1.jpg

          RECIPE_NAME         RUN_ID         SCAN_ENDTIME  \
196046  B140UAN08-TFT  -2116675097.0  2026-04-08T07:31:14

             SCAN_STARTTIME   SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
196046  2026-04-08T07:30:48  JT6A3XT7T  N  CELL  CAPIC507                2.0
runid fail:  -2116675098.0 20260408064822
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36413       12.0         OK          12.0   True  L6A  M340QAR1A

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36413  M340QAR1A-TFT  -2116675098.0 2026-04-08 06:48:44

                SCAN_STARTTIME        SHEET_ID STAGE   TOOL_ID  \
36413  2026-04-08 06:48:22.000  20260408064822  CELL  CAPIC407

      TOTAL_DEFECT_COUNT TYPE
36413                1.0  TFT
-----only 'SHEET_ID' also fail----
runid fail:  -2116675174.0 JT6A3XT7C
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
36357       36.0         OK          35.0   True  L6A  B140UAN08

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
36357  B140UAN08-TFT  -2116675174.0 2026-04-08 07:17:26

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
36357  2026-04-08 07:17:01.000  JT6A3XT7C  CELL  CAPIC507                3.0

      TYPE
36357  TFT
-----only 'SHEET_ID' also fail----
defect count fail
-2116676106.0 20260408041908
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
35413       12.0         OK          12.0   True  L6A  M340QAR1A

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
35413  M340QAR1A-TFT  -2116676106.0 2026-04-08 04:19:31

                SCAN_STARTTIME        SHEET_ID STAGE   TOOL_ID  \
35413  2026-04-08 04:19:09.000  20260408041908  CELL  CAPIC407

      TOTAL_DEFECT_COUNT TYPE
35413                1.0  TFT
2

          COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
190880  -1337.086   -155.043   True                   1.0                S
190881  -1039.196  -1101.421   True                   2.0                M

        FAB FRONT_REVERSE                                            IMG_URL  \
190880  L6A            1P  http://10.97.138.73/capic407-si/20260408/20260...
190881  L6A            1P

          RECIPE_NAME         RUN_ID         SCAN_ENDTIME  \
190880  M340QAR1A-TFT  -2116676106.0  2026-04-08T04:19:31
190881  M340QAR1A-TFT  -2116676106.0  2026-04-08T04:19:31

             SCAN_STARTTIME        SHEET_ID SP STAGE   TOOL_ID  \
190880  2026-04-08T04:19:09  20260408041908  N  CELL  CAPIC407
190881  2026-04-08T04:19:09  20260408041908  N  CELL  CAPIC407

       TOTAL_DEFECT_COUNT
190880                1.0
190881                1.0
runid fail:  -2116676107.0 20260408045650
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
35424       36.0         OK          36.0   True  L6A  B140UAN08

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
35424  B140UAN08-TFT  -2116676107.0 2026-04-08 04:57:16

                SCAN_STARTTIME        SHEET_ID STAGE   TOOL_ID  \
35424  2026-04-08 04:56:50.000  20260408045650  CELL  CAPIC507

      TOTAL_DEFECT_COUNT TYPE
35424                2.0  TFT
-----only 'SHEET_ID' also fail----
runid fail:  -2116676797.0 LV6A3WJ1T
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
34668       18.0         OK          17.0   True  L6A  M215HAN01

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
34668  M215HAN01-TFT  -2116676797.0 2026-04-08 02:01:13

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
34668  2026-04-08 02:00:52.000  LV6A3WJ1T  CELL  CAPIC307                1.0

      TYPE
34668  TFT
-----only 'SHEET_ID' also fail----
runid fail:  -2116676852.0 LV6A3WJ1E
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
34614       18.0         OK          17.0   True  L6A  M215HAN01

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
34614  M215HAN01-TFT  -2116676852.0 2026-04-08 01:51:28

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
34614  2026-04-08 01:51:05.000  LV6A3WJ1E  CELL  CAPIC307                1.0

      TYPE
34614  TFT
-----only 'SHEET_ID' also fail----
defect count fail
-2116680135.0 AE1U840115
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
31364       36.0         OK          36.0   True  L6A  B140UAN08

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
31364  B140UAN08-CF  -2116680135.0 2026-04-07 12:25:09

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
31364  2026-04-07 12:24:42.000  AE1U840115  CELL  CAPIC507                1.0

      TYPE
31364   CF
8

          COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
167372   -722.724    -165.98   True                   1.0                S
167373   -123.042   -792.093   True                   2.0                M
167374   -184.079  -1421.423   True                   3.0                S
167375  -1434.364   -994.279   True                   4.0                S
167376   -801.237  -1188.264   True                   5.0                S
167377    -368.95   -485.738   True                   6.0                S
167378   -473.295   -969.091   True                   7.0                S
167379   -440.057  -1395.852   True                   8.0                S

        FAB FRONT_REVERSE                                        IMG_URL  \
167372  L6A            1N  http://10.97.138.17/20260407/AE1U840115/1.jpg
167373  L6A            1P
167374  L6A            1P
167375  L6A            1P
167376  L6A            1P
167377  L6A            1P
167378  L6A            1P
167379  L6A            1P

         RECIPE_NAME         RUN_ID         SCAN_ENDTIME       SCAN_STARTTIME  \
167372  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167373  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167374  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167375  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167376  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167377  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167378  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42
167379  B140UAN08-CF  -2116680135.0  2026-04-07T12:25:09  2026-04-07T12:24:42

          SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
167372  AE1U840115  N  CELL  CAPIC507                1.0
167373  AE1U840115  N  CELL  CAPIC507                1.0
167374  AE1U840115  N  CELL  CAPIC507                1.0
167375  AE1U840115  N  CELL  CAPIC507                1.0
167376  AE1U840115  N  CELL  CAPIC507                1.0
167377  AE1U840115  N  CELL  CAPIC507                1.0
167378  AE1U840115  N  CELL  CAPIC507                1.0
167379  AE1U840115  N  CELL  CAPIC507                1.0
runid fail:  -2116680137.0 AL5H1427P8
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
31348       18.0         OK          18.0   True  L6A  G215HVN01

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
31348  G215HVN01-CF  -2116680137.0 2026-04-07 12:17:08

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
31348  2026-04-07 12:16:46.000  AL5H1427P8  CELL  CAPIC207                8.0

      TYPE
31348   CF
-----only 'SHEET_ID' also fail----
runid fail:  -2116681356.0 LV6A3WW8D
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
30131       18.0         OK          17.0   True  L6A  M215HAN01

         RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
30131  M215HAN01-TFT  -2116681356.0 2026-04-07 05:44:21

                SCAN_STARTTIME   SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
30131  2026-04-07 05:43:58.000  LV6A3WW8D  CELL  CAPIC107                1.0

      TYPE
30131  TFT
-----only 'SHEET_ID' also fail----
defect count fail
-2116681929.0 AL5H1428H6
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
29568       18.0         OK          18.0   True  L6A  G215HVN01

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
29568  G215HVN01-CF  -2116681929.0 2026-04-07 02:26:00

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
29568  2026-04-07 02:25:38.000  AL5H1428H6  CELL  CAPIC207                7.0

      TYPE
29568   CF
14

          COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
162230  -1036.981   -470.501   True                   1.0                S
162231  -1036.981   -470.501   True                   1.0                S
162232  -1259.182  -1637.878   True                   2.0                M
162233  -1259.182  -1637.878   True                   2.0                M
162234  -1264.034  -1689.404   True                   3.0                S
162235  -1264.034  -1689.404   True                   3.0                S
162236   -648.446   -810.046   True                   4.0                S
162237   -648.446   -810.046   True                   4.0                S
162238   -1341.77    -978.91   True                   5.0                S
162239   -1341.77    -978.91   True                   5.0                S
162240  -1367.586  -1195.282   True                   6.0                S
162241  -1367.586  -1195.282   True                   6.0                S
162242    -900.84   -759.854   True                   7.0                S
162243    -900.84   -759.854   True                   7.0                S

        FAB FRONT_REVERSE                                         IMG_URL  \
162230  L6A            1P  http://10.97.138.179/20260406/AL5H1428H6/1.jpg
162231  L6A            1P  http://10.97.138.179/20260407/AL5H1428H6/1.jpg
162232  L6A            1N  http://10.97.138.179/20260406/AL5H1428H6/2.jpg
162233  L6A            1N  http://10.97.138.179/20260407/AL5H1428H6/2.jpg
162234  L6A            1N  http://10.97.138.179/20260406/AL5H1428H6/3.jpg
162235  L6A            1N  http://10.97.138.179/20260407/AL5H1428H6/3.jpg
162236  L6A            1P  http://10.97.138.179/20260406/AL5H1428H6/4.jpg
162237  L6A            1P  http://10.97.138.179/20260407/AL5H1428H6/4.jpg
162238  L6A            1P  http://10.97.138.179/20260406/AL5H1428H6/5.jpg
162239  L6A            1P  http://10.97.138.179/20260407/AL5H1428H6/5.jpg
162240  L6A            1P  http://10.97.138.179/20260406/AL5H1428H6/6.jpg
162241  L6A            1P  http://10.97.138.179/20260407/AL5H1428H6/6.jpg
162242  L6A            1P  http://10.97.138.179/20260406/AL5H1428H6/7.jpg
162243  L6A            1P  http://10.97.138.179/20260407/AL5H1428H6/7.jpg

         RECIPE_NAME         RUN_ID         SCAN_ENDTIME       SCAN_STARTTIME  \
162230  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162231  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162232  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162233  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162234  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162235  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162236  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162237  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162238  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162239  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162240  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162241  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162242  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38
162243  G215HVN01-CF  -2116681929.0  2026-04-07T02:26:00  2026-04-07T02:25:38

          SHEET_ID SP STAGE   TOOL_ID TOTAL_DEFECT_COUNT
162230  AL5H1428H6  N  CELL  CAPIC207                7.0
162231  AL5H1428H6  N  CELL  CAPIC207                7.0
162232  AL5H1428H6  N  CELL  CAPIC207                7.0
162233  AL5H1428H6  N  CELL  CAPIC207                7.0
162234  AL5H1428H6  N  CELL  CAPIC207                7.0
162235  AL5H1428H6  N  CELL  CAPIC207                7.0
162236  AL5H1428H6  N  CELL  CAPIC207                7.0
162237  AL5H1428H6  N  CELL  CAPIC207                7.0
162238  AL5H1428H6  N  CELL  CAPIC207                7.0
162239  AL5H1428H6  N  CELL  CAPIC207                7.0
162240  AL5H1428H6  N  CELL  CAPIC207                7.0
162241  AL5H1428H6  N  CELL  CAPIC207                7.0
162242  AL5H1428H6  N  CELL  CAPIC207                7.0
162243  AL5H1428H6  N  CELL  CAPIC207                7.0
defect count fail
-2116681932.0 AL5H1428CJ
      CHIP_COUNT CHIP_JUDGE CHIP_OK_COUNT DEFECT  FAB   MODEL_NO  \
29567       18.0         OK          17.0   True  L6A  G215HVN01

        RECIPE_NAME         RUN_ID        SCAN_ENDTIME  \
29567  G215HVN01-CF  -2116681932.0 2026-04-07 02:24:22

                SCAN_STARTTIME    SHEET_ID STAGE   TOOL_ID TOTAL_DEFECT_COUNT  \
29567  2026-04-07 02:23:59.000  AL5H1428CJ  CELL  CAPIC207               14.0

      TYPE
29567   CF
28

         COORD_X    COORD_Y DEFECT DEFECT_AREA DEFECT_ID DEFECT_SIZE_TYPE  \
162174   -127.26    -811.33   True                   1.0                M
162175   -127.26    -811.33   True                   1.0                M
162176  -179.797   -854.654   True                   2.0                M
162177  -179.797   -854.654   True                   2.0                M
162178    -55.17   -875.658   True                   3.0                M

In [ ]:
[{"run_id": "-2116686255.0", "glass_id": "20260405163152", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686250.0", "glass_id": "N46A2NX51", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686249.0", "glass_id": "N46A2NX52", "summary_defect_count": 2, "raw_defect_count": 2, "S": 0, "M": 1, "L": 1, "O": 0, "raw_matched": true}, {"run_id": "-2116686210.0", "glass_id": "N46A2NX53", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686209.0", "glass_id": "N46A2NX54", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686243.0", "glass_id": "N46A2NX5X", "summary_defect_count": 2, "raw_defect_count": 2, "S": 1, "M": 1, "L": 0, "O": 0, "raw_matched": true}, {"run_id": "-2116686242.0", "glass_id": "N46A2NX5Y", "summary_defect_count": 5, "raw_defect_count": 5, "S": 1, "M": 2, "L": 0, "O": 2, "raw_matched": true},
  {"run_id": "-2116686055.0", "glass_id": "N46A3JG8A", "summary_defect_count": 1, "raw_defect_count": 1, "S": 0, "M": 1, "L": 0, "O": 0, "raw_matched": true}, {"run_id": "-2116686054.0", "glass_id": "N46A3JG8B", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686053.0", "glass_id": "N46A3JG8C", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686052.0", "glass_id": "N46A3JG8D", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}, {"run_id": "-2116686051.0", "glass_id": "N46A3JG8E", "summary_defect_count": 0, "raw_defect_count": 0, "S": 0, "M": 0, "L": 0, "O": 0, "raw_matched": false}]

In [28]:
print(non_id ,non_sheet ,same1,same2)

0 44 23 16232

In [2]:
d_tbns = dbhandler.list_tables()
print(d_tbns)

c_tbns = cim_dbhandler.list_tables()
c_tbns[:3]

o_tbns = old_dbhandler.list_tables()
[v for v in o_tbns if 'spec_' in v]

2026-02-12 14:51:44,203 - INFO - [list_tables] 成功取得資料表名稱，共 4 張表。
2026-02-12 14:51:44,208 - INFO - [list_tables] 成功取得資料表名稱，共 69 張表。
2026-02-12 14:51:44,236 - INFO - [list_tables] 成功取得資料表名稱，共 205 張表。

['default_spec_table', 'density_summary_202601', 'density_summary_202602', 'fix_spec_table_202602']

['aoi_density_fixed_spec_table',
 'aoi_density_spec_for_aoimonitor',
 'aoi_spec_for_aoimonitor',
 'spec_pro_update__table',
 'spec_pro_update_history']

In [8]:
60*24

1440

In [4]:
#spec_df = old_dbhandler.get_table('aoi_density_spec_for_aoimonitor')
#spec_df[(spec_df['line_id'] == 'CAPIC300') & (spec_df['MODEL_ID'] == 'Z335XAN01') ]
spec_df = dbhandler.get_table('fix_spec_table_202602')
spec_df.iloc[-1,:].to_dict()

{'line_id': 'CAPIC200',
 'aoi': 'aoi100',
 'model': 'G215HVN1C',
 'recipe_id': '608',
 'glass_type': 'CF',
 'adc_def_code': 'SPS',
 'defect_size': 'OLM',
 'total_glass_cnt': 28,
 'defect_cnt': 0.0,
 'density': 0.0,
 'overD': 0.0,
 'removed_glasses': 0,
 'removed_defects': 0.0,
 'final_glass_cnt': 28,
 'final_defect_cnt': 0.0,
 'final_density': 0.0,
 'std': 0.0,
 'OOC': 0.0,
 'OOS': 0.0,
 'GEN_DT': Timestamp('2026-02-10 08:00:03'),
 'PERIOD_START': Timestamp('2025-11-12 07:30:00'),
 'PERIOD_END': Timestamp('2026-02-10 07:30:00'),
 'DAYS': 90}

In [2]:
c_tb = cim_dbhandler.get_table('cim_pi_glass_202601')#'cim_defect_202512_aoi100_capic100'
print(c_tb.iloc[0,:].to_dict())
d_tb = dbhandler.get_table('density_summary_202602')
print(len(d_tb))
d_tb.iloc[0,:].to_dict()

{'sheet_id_chip_id': 'YM5ACMK5A', 'test_time': Timestamp('2025-12-24 00:15:34'), 'model_no': 'B156HAN2U', 'op_id': 'KOUID', 'abbr_cat': 'TFT', 'recipe_id': '4309', 'cassette_id': 'AA0023', 'aoi': 'CAAOI202', 'total_defect_qty': 81, 'defect_size_o_qty': 0, 'defect_size_l_qty': 1, 'defect_size_m_qty': 28, 'defect_size_s_qty': 52, 'line_id': 'CAPIC100', 'pi_time': Timestamp('2026-01-05 22:46:41'), 'pi_hour': Timestamp('2026-01-05 22:00:00'), 'pi_type': 'BPI'}
2757

{'line_id': 'CAPIC100',
 'aoi': 'aoi200',
 'model': 'B156HAN2U',
 'glass_type': 'TFT',
 'recipe_id': '0309',
 'pi_hour': Timestamp('2026-02-01 03:00:00'),
 'adc_def_code': 'NPI_OIL',
 'defect_cnt': 4,
 'glass_cnt': 7,
 'density': 0.571,
 'def_glass_cnt': 2,
 'small_defect_count': 1,
 'middle_defect_count': 3,
 'large_defect_count': 0,
 'over_defect_count': 0,
 'glass': 'YL6A1Q63A,YL6A1Q63B,YL6A1Q63C,YL6A1Q63D,YL6A1Q63E,YL6A1Q63F,YL6A1Q63G',
 'glass_size_detail': '{"YL6A1Q63A": {"S": 0, "M": 1, "L": 0, "O": 0, "T": 1}, "YL6A1Q63B": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "YL6A1Q63C": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "YL6A1Q63D": {"S": 1, "M": 2, "L": 0, "O": 0, "T": 3}, "YL6A1Q63E": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "YL6A1Q63F": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}, "YL6A1Q63G": {"S": 0, "M": 0, "L": 0, "O": 0, "T": 0}}',
 'shift': '{}',
 'comment': '',
 'action': '',
 'Editor': '',
 'modify_time': '2026-02-06 13:54:13'}

In [ ]:
d_tb.columns
cols = ['line_id', 'aoi', 'model', 'glass_type', 'recipe_id', 'pi_hour','adc_def_code', 'density',
  'comment', 'action', 'Editor', 'modify_time',
       ]
d_tb[cols]

,line_id,aoi,model,glass_type,recipe_id,pi_hour,adc_def_code,density,comment,action,Editor,modify_time
0,CAPIC100,aoi200,B156HAN2U,TFT,0309,2026-02-01 03:00:00,NPI_OIL,0.571,,,,2026-02-06 13:54:13
1,CAPIC100,aoi200,B156HAN2U,TFT,0309,2026-02-01 03:00:00,NPI_TFT,0.429,,,,2026-02-06 13:54:13
2,CAPIC100,aoi200,B156HAN2U,TFT,0309,2026-02-01 03:00:00,Not_Found,1.429,,,,2026-02-06 13:54:13
3,CAPIC100,aoi200,B156HAN2U,TFT,0309,2026-02-01 03:00:00,PIS With Particle,1.286,,,,2026-02-06 13:54:13
4,CAPIC100,aoi200,B156HAN2U,TFT,0309,2026-02-01 03:00:00,PI_Spot_NP,0.143,,,,2026-02-06 13:54:13
...,...,...,...,...,...,...,...,...,...,...,...,...
2752,CAPIC700,aoi200,M270QAN06,TFT,4234,2026-02-07 05:00:00,Not_Found,0.357,,,,2026-02-07 16:05:48
2753,CAPIC700,aoi200,M270QAN06,TFT,4234,2026-02-07 05:00:00,OP_Defect,26.429,,,,2026-02-07 16:05:48
2754,CAPIC700,aoi200,M270QAN06,TFT,4234,2026-02-07 05:00:00,PI_Gel,0.143,,,,2026-02-07 16:05:48
2755,CAPIC700,aoi200,M270QAN06,TFT,4234,2026-02-07 05:00:00,Polymer,0.071,,,,2026-02-07 16:05:48
2756,CAPIC700,aoi200,M270QAN06,TFT,4234,2026-02-07 05:00:00,SSIU_Polymer,0.071,,,,2026-02-07 16:05:48

In [13]:
group_cols = ["line_id", "aoi",'model_no', "abbr_cat", "recipe_id", "pi_hour"]
sort_cols = ["pi_time", "test_time"]
order_cols = group_cols + ["sheet_id_chip_id"] + sort_cols
tmp = c_tb.copy()
tmp = tmp.sort_values(order_cols, ascending=True)
# per (group + glass) keep latest
tmp = tmp.drop_duplicates(subset=group_cols + ["sheet_id_chip_id"], keep="last")
print(f'[keep latest]ori rows: {len(c_tb)}, drop rows: : {len(tmp)}')

[keep latest]ori rows: 17160, drop rows: : 15755

In [11]:
d_tb[d_tb['glass'].str.contains('AP0H11145N')]
c_tb[c_tb['sheet_id_chip_id'].str.contains('AP0H11145N')].to_dict()

{'sheet_id_chip_id': {1155: 'AP0H11145N'},
 'test_time': {1155: Timestamp('2026-02-03 08:20:08')},
 'model_no': {1155: 'G240HW01_VX'},
 'op_id': {1155: 'PI AOI'},
 'abbr_cat': {1155: 'CF'},
 'recipe_id': {1155: '602'},
 'cassette_id': {1155: 'CA0346'},
 'aoi': {1155: 'CAPIT203'},
 'total_defect_qty': {1155: 120},
 'defect_size_o_qty': {1155: 0},
 'defect_size_l_qty': {1155: 2},
 'defect_size_m_qty': {1155: 6},
 'defect_size_s_qty': {1155: 112},
 'line_id': {1155: 'CAPIC200'},
 'pi_time': {1155: Timestamp('2026-02-03 05:59:55')},
 'pi_hour': {1155: Timestamp('2026-02-03 05:00:00')},
 'pi_type': {1155: 'API'}}

In [8]:
from dataclasses import dataclass, field
from typing import Dict, Tuple, List, Optional, Iterable
class Config:
    # connection
    host: str = "10.97.142.217"
    username: str = "l6a01_user"
    password: str = "l6a01$user"

    # dbs
    src_db: str = "cim_piaoi"        # read only
    out_db: str = "piaoi_density"    # write

    # source tables template
    summary_table_tpl: str = "cim_pi_glass_yyyymm"           # month table
    defect_table_tpl: str = "cim_defect_yyyymm_aoi_line"     # month table

    # output tables template (per month of pi_hour)
    out_table_tpl: str = "density_summary_yyyymm"

    # group columns (after rename)
    group_cols: Tuple[str, ...] = ("line_id", "aoi", "model", "glass_type", "recipe_id", "pi_hour")

    # sort for latest measurement per glass
    sort_cols: Tuple[str, ...] = ("scan_time", "pi_time")  # scan_time == test_time renamed

    # aoi mapping
    aoi_map: Dict[str, str] = field(default_factory=lambda: {
        "CAPIT203": "aoi100",
        "CAAOI202": "aoi200",
        "CAAOI300": "aoi300",
    })

    # summary column mapping (source -> standardized)
    summary_coldict={
        "line_id": "line_id",
        "aoi": "aoi",
        "model_no": "model",
        "abbr_cat": "glass_type",
        "recipe_id": "recipe_id",
        "pi_hour": "pi_hour",
        "pi_type": "pi_type",
        "sheet_id_chip_id": "glass_id",
        "total_defect_qty": "total_defect_count",
        "pi_time": "pi_time",
        "test_time": "scan_time",
    }

    # defect column mapping (source -> standardized)
    defect_coldict: Dict[str, str] = field(default_factory=lambda: {
        "sheet_id_chip_id": "glass_id",
        "chip_id": "chip_name",
        "test_time": "scan_time",
        "defect_size": "defect_size",
        "pox_x1": "x",
        "pox_y1": "y",
        "image_file_path": "pic_path",
        "image_file_name": "pic_name",
        "retype_def_code": "retype_code",
        "adc_def_code": "adc_def_code",
        "pi_time": "pi_time",
        "pi_hour": "pi_hour",
    })

    # query batching
    batch_size: int = 800

    # loop mode
    loop_minutes: int = 10
    # 每次 loop 回看多久（避免同一小時內晚到資料漏掉 -> 覆蓋用）
    lookback_minutes: int = 180  # 建議 >= 120

    # write
    write_out: bool = True
cfg = Config()

In [11]:
60*24

1440

In [8]:
summary = cim_dbhandler.get_table('cim_pi_glass_202602')
summary .head()

,sheet_id_chip_id,test_time,model_no,op_id,abbr_cat,recipe_id,cassette_id,aoi,total_defect_qty,defect_size_o_qty,defect_size_l_qty,defect_size_m_qty,defect_size_s_qty,line_id,pi_time,pi_hour,pi_type
0,AG0UA10P6J,2026-02-01 02:02:35,B160UAN4A_VB,PI AOI,CF,209,CA0081,CAPIT203,6,0,0,1,5,CAPIC700,2026-02-01 01:12:43,2026-02-01 01:00:00,API
1,AG0UA10NUY,2026-02-01 02:05:05,B160UAN4A_VB,PI AOI,CF,209,CA0081,CAPIT203,15,0,2,2,11,CAPIC700,2026-02-01 01:12:43,2026-02-01 01:00:00,API
2,AG0UA10NUU,2026-02-01 02:07:42,B160UAN4A_VB,PI AOI,CF,209,CA0081,CAPIT203,19,2,0,5,12,CAPIC700,2026-02-01 01:12:43,2026-02-01 01:00:00,API
3,AG0UA10NUX,2026-02-01 02:10:19,B160UAN4A_VB,PI AOI,CF,209,CA0081,CAPIT203,15,0,0,2,13,CAPIC700,2026-02-01 01:12:43,2026-02-01 01:00:00,API
4,AG0UA10P6V,2026-02-01 02:12:54,B160UAN4A_VB,PI AOI,CF,209,CA0081,CAPIT203,14,0,0,3,11,CAPIC700,2026-02-01 01:12:43,2026-02-01 01:00:00,API

In [9]:
need_cols = ['pi_time', 'sheet_id_chip_id', 'test_time',  'total_defect_qty', 'pi_hour', 'pi_type']

cast_cols =['line_id', 'aoi','model_no',  'op_id', 'abbr_cat', 'recipe_id', 'cassette_id']
for (main_keys), rows in summary.groupby(cast_cols):
    
    if len(rows['pi_hour'].unique())>1:
        print('old', rows['pi_hour'].unique())
        earliest_tt = rows['pi_hour'].min()
        others = rows[rows['pi_hour'] != earliest_tt]
        summary.loc[others.index, ['pi_hour']] = earliest_tt
        print(summary.loc[others.index, summary.columns]['pi_hour'].unique())

old <DatetimeArray>
['2026-02-01 04:00:00', '2026-02-01 05:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-01 04:00:00']
Length: 1, dtype: datetime64[ns]
old <DatetimeArray>
['2026-02-01 04:00:00', '2026-02-01 05:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-01 04:00:00']
Length: 1, dtype: datetime64[ns]
old <DatetimeArray>
['2026-02-02 00:00:00', '2026-02-02 02:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-02 00:00:00']
Length: 1, dtype: datetime64[ns]
old <DatetimeArray>
['2026-02-02 04:00:00', '2026-02-02 14:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-02 04:00:00']
Length: 1, dtype: datetime64[ns]
old <DatetimeArray>
['2026-02-01 05:00:00', '2026-02-03 22:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-01 05:00:00']
Length: 1, dtype: datetime64[ns]
old <DatetimeArray>
['2026-02-02 04:00:00', '2026-02-02 14:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-02 04:00:00']
Length: 1, dtype: datetime64[ns]
old <DatetimeArray>
['2026-02-01 05:00:00', '2026-02-03 22:00:00']
Length: 2, dtype: datetime64[ns]
<DatetimeArray>
['2026-02-01 05:00:00']
Length: 1, dtype: datetime64[ns]

In [10]:
for (main_keys), rows in summary.groupby(cast_cols):
    
    if len(rows['pi_hour'].unique())>1:
        print('old', rows['pi_hour'].unique())

In [9]:
need_cols = ["line_id", "aoi", "model", "glass_type", "recipe_id", "pi_hour","adc_def_code",
              "defect_cnt", "glass_cnt", "density", "def_glass_cnt",
                "glass","glass_size_detail","small_defect_count", "middle_defect_count", "large_defect_count", "over_defect_count"]
df = dbhandler.get_table('density_summary_202601')
df = df[need_cols ]
df.iloc[0,:].to_dict()

{'line_id': 'CAPIC100',
 'aoi': 'aoi100',
 'model': 'B156HTN06',
 'glass_type': 'CF',
 'recipe_id': '812',
 'pi_hour': Timestamp('2026-01-02 05:00:00'),
 'adc_def_code': 'NPI_TFT',
 'defect_cnt': 7,
 'glass_cnt': 1,
 'density': 7.0,
 'def_glass_cnt': 1,
 'glass': 'AF6H6C05RL',
 'glass_size_detail': '{"AF6H6C05RL": {"S": 3, "M": 4, "L": 0, "O": 0, "T": 7}}',
 'small_defect_count': 3,
 'middle_defect_count': 4,
 'large_defect_count': 0,
 'over_defect_count': 0}

,line_id,aoi,model,glass_type,recipe_id,pi_hour,adc_def_code,defect_cnt,glass_cnt,density,...,small_defect_count,middle_defect_count,large_defect_count,over_defect_count,glass,glass_size_detail,comment,action,Editor,modify_time
0,CAPIC100,aoi100,B156HTN06,CF,812,2026-01-02 05:00:00,NPI_TFT,7,1,7.0,...,3,4,0,0,AF6H6C05RL,"{""AF6H6C05RL"": {""S"": 3, ""M"": 4, ""L"": 0, ""O"": 0...",,,,2026-02-04 10:04:16
1,CAPIC100,aoi100,B156HTN06,CF,812,2026-01-02 05:00:00,OP_Defect,2,1,2.0,...,2,0,0,0,AF6H6C05RL,"{""AF6H6C05RL"": {""S"": 2, ""M"": 0, ""L"": 0, ""O"": 0...",,,,2026-02-04 10:04:16
2,CAPIC100,aoi100,B156HTN06,CF,812,2026-01-02 05:00:00,Polymer,2,1,2.0,...,1,1,0,0,AF6H6C05RL,"{""AF6H6C05RL"": {""S"": 1, ""M"": 1, ""L"": 0, ""O"": 0...",,,,2026-02-04 10:04:16
3,CAPIC100,aoi100,B156HTN06,CF,812,2026-01-02 05:00:00,SSIU_Polymer,238,1,238.0,...,219,19,0,0,AF6H6C05RL,"{""AF6H6C05RL"": {""S"": 219, ""M"": 19, ""L"": 0, ""O""...",,,,2026-02-04 10:04:16
4,CAPIC100,aoi100,B156HTN06,CF,812,2026-01-02 10:00:00,BM_Cover,4,1,4.0,...,3,1,0,0,AF6H6C06K3,"{""AF6H6C06K3"": {""S"": 3, ""M"": 1, ""L"": 0, ""O"": 0...",,,,2026-02-04 10:04:16